# Generated by Django 4.1.7 on 2023-03-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_delete_cutomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=200)),
                ('last_Name', models.CharField(max_length=200)),
                ('time_log', models.TimeField(help_text='enter the exact time')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
